// Generated by CoffeeScript 1.11.1
(function() {
  var Cursor;

  Cursor = (function() {
    function Cursor() {}


    /* !pragma coverage-skip-next */

    Cursor.prototype.getTotalResultCount = function() {
      throw new Error('`getTotalResultCount` called on abstract Cursor');
    };


    /* !pragma coverage-skip-next */

    Cursor.prototype.getRemainingResultCount = function() {
      throw new Error('`getRemainingResultCount` called on abstract Cursor');
    };

    return Cursor;

  })();

  module.exports = Cursor;

}).call(this);
