// Generated by CoffeeScript 1.11.1
(function() {
  var ANY, ARRAY, BOOLEAN, DATE, FLOAT, INTEGER, OBJECT, STRING, TEXT;

  STRING = 'STRING';

  TEXT = 'TEXT';

  BOOLEAN = 'BOOLEAN';

  INTEGER = 'INTEGER';

  FLOAT = 'FLOAT';

  OBJECT = 'OBJECT';

  ARRAY = function(subtype) {
    return "ARRAY(" + subtype + ")";
  };

  DATE = 'DATE';

  ANY = 'ANY';

  module.exports = {
    STRING: STRING,
    TEXT: TEXT,
    BOOLEAN: BOOLEAN,
    INTEGER: INTEGER,
    FLOAT: FLOAT,
    OBJECT: OBJECT,
    ARRAY: ARRAY,
    DATE: DATE,
    ANY: ANY
  };

}).call(this);
