'use strict';

exports.__esModule = true;
exports.createStandardInstanceClassForBoundModel = exports.Query = exports.ResultSet = exports.Migration = exports.Cursor = exports.Util = exports.Instance = exports.Field = exports.BoundModel = exports.Backend = exports.Corpus = exports.Model = exports.ANY = exports.DATE = exports.ARRAY = exports.OBJECT = exports.FLOAT = exports.INTEGER = exports.BOOLEAN = exports.TEXT = exports.STRING = undefined;

var _Model = require('./Model');

var _Model2 = _interopRequireDefault(_Model);

var _Corpus = require('./Corpus');

var _Corpus2 = _interopRequireDefault(_Corpus);

var _Backend = require('./Backend');

var _Backend2 = _interopRequireDefault(_Backend);

var _BoundModel = require('./BoundModel');

var _BoundModel2 = _interopRequireDefault(_BoundModel);

var _Field = require('./Field');

var _Field2 = _interopRequireDefault(_Field);

var _Instance = require('./Instance');

var _Instance2 = _interopRequireDefault(_Instance);

var _Util = require('./Util');

var Util = _interopRequireWildcard(_Util);

var _Cursor = require('./Cursor');

var _Cursor2 = _interopRequireDefault(_Cursor);

var _Migration = require('./Migration');

var _Migration2 = _interopRequireDefault(_Migration);

var _ResultSet = require('./ResultSet');

var _ResultSet2 = _interopRequireDefault(_ResultSet);

var _Query = require('./Query');

var _Query2 = _interopRequireDefault(_Query);

var _StandardInstance = require('./StandardInstance');

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 1.11.1
var STRING = exports.STRING = 'STRING';

var TEXT = exports.TEXT = 'TEXT';

var BOOLEAN = exports.BOOLEAN = 'BOOLEAN';

var INTEGER = exports.INTEGER = 'INTEGER';

var FLOAT = exports.FLOAT = 'FLOAT';

var OBJECT = exports.OBJECT = 'OBJECT';

var ARRAY = exports.ARRAY = function (subtype) {
  return "ARRAY(" + subtype + ")";
};

var DATE = exports.DATE = 'DATE';

var ANY = exports.ANY = 'ANY';

exports.Model = _Model2.default;
exports.Corpus = _Corpus2.default;
exports.Backend = _Backend2.default;
exports.BoundModel = _BoundModel2.default;
exports.Field = _Field2.default;
exports.Instance = _Instance2.default;
exports.Util = Util;
exports.Cursor = _Cursor2.default;
exports.Migration = _Migration2.default;
exports.ResultSet = _ResultSet2.default;
exports.Query = _Query2.default;
exports.createStandardInstanceClassForBoundModel = _StandardInstance.createStandardInstanceClassForBoundModel;