// Generated by CoffeeScript 1.11.1
(function() {
  var FieldTypes;

  FieldTypes = require('./FieldTypes');

  module.exports = Object.assign({
    Model: require('./Model'),
    Corpus: require('./Corpus'),
    Backend: require('./Backend'),
    BoundModel: require('./BoundModel'),
    Field: require('./Field'),
    Instance: require('./Instance'),
    Util: require('./Util'),
    Cursor: require('./Cursor'),
    Migration: require('./Migration'),
    ResultSet: require('./ResultSet'),
    Query: require('./Query'),
    createStandardInstanceClassForBoundModel: (require('./StandardInstance')).createStandardInstanceClassForBoundModel
  }, FieldTypes);

}).call(this);
