// Generated by CoffeeScript 1.11.1
(function() {
  var Migration;

  Migration = (function() {
    function Migration(corpus, backend) {
      this.corpus = corpus;
      this.backend = backend;
    }

    Migration.prototype.prepare = function() {};

    Migration.prototype.getMigrationPlan = function() {};

    return Migration;

  })();

  module.exports = Migration;

}).call(this);
