// Generated by CoffeeScript 1.11.1
(function() {
  var Query;

  module.exports = Query = (function() {
    function Query(spec) {
      this.spec = spec;
    }

    return Query;

  })();

}).call(this);
