// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    dataValues: true,
    set: true,
    get: true,
    setDataValue: true,
    getDataValue: true,
    changed: true,
    save: true,
    destroy: true
  };

}).call(this);
