// Generated by CoffeeScript 1.11.1
import Model from './Model';

import Corpus from './Corpus';

import Backend from './Backend';

import BoundModel from './BoundModel';

import Field from './Field';

import Instance from './Instance';

import * as Util from './Util';

import Cursor from './Cursor';

import Migration from './Migration';

import ResultSet from './ResultSet';

import Query from './Query';

import { createStandardInstanceClassForBoundModel } from './StandardInstance';

export var STRING = 'STRING';

export var TEXT = 'TEXT';

export var BOOLEAN = 'BOOLEAN';

export var INTEGER = 'INTEGER';

export var FLOAT = 'FLOAT';

export var OBJECT = 'OBJECT';

export var ARRAY = function (subtype) {
  return "ARRAY(" + subtype + ")";
};

export var DATE = 'DATE';

export var ANY = 'ANY';

export { Model, Corpus, Backend, BoundModel, Field, Instance, Util, Cursor, Migration, ResultSet, Query, createStandardInstanceClassForBoundModel };