// Generated by CoffeeScript 1.11.1
var Migration;

export default Migration = function () {
  function Migration(corpus, backend) {
    this.corpus = corpus;
    this.backend = backend;
  }

  Migration.prototype.prepare = function () {};

  Migration.prototype.getMigrationPlan = function () {};

  return Migration;
}();