// Generated by CoffeeScript 1.11.1
var reservedWords;

export default reservedWords = {
  dataValues: true,
  set: true,
  get: true,
  setDataValue: true,
  getDataValue: true,
  changed: true,
  save: true,
  destroy: true
};