// Generated by CoffeeScript 1.11.1
var ResultSet;

export default ResultSet = function () {
  function ResultSet() {}

  ResultSet.prototype.isEmpty = function () {
    return this.getResultCount() === 0;
  };

  ResultSet.prototype.getResultCount = function () {
    if (this.results) {
      return this.results.length;
    } else {
      return 0;
    }
  };

  /* !pragma coverage-skip-next */

  ResultSet.prototype.getTotalResultCount = function () {
    throw new Error('`getTotalResultCount` called on abstract ResultSet');
  };

  ResultSet.prototype.getResults = function () {
    return this.results || [];
  };

  /* !pragma coverage-skip-next */

  ResultSet.prototype.getCursor = function () {
    throw new Error('`getCursor` called on abstract ResultSet');
  };

  /* !pragma coverage-skip-next */

  ResultSet.prototype.hasMore = function () {
    return this.getCursor() != null;
  };

  return ResultSet;
}();