// Generated by CoffeeScript 1.11.1
export var isPrimitive = function (v) {
  var t;
  t = typeof v;
  if (t === 'string' || t === 'number' || t === 'boolean') {
    return true;
  } else {
    return false;
  }
};

/* !pragma coverage-skip-next */

export var get = function (object, path) {
  var index, length;
  index = 0;
  length = path.length;
  while (object != null && index < length) {
    object = object[path[index++]];
  }
  if (index === length) {
    return object;
  } else {
    return void 0;
  }
};

/* !pragma coverage-skip-next */

export var set = function (object, path, val) {
  var index, length;
  index = 0;
  length = path.length;
  while (object != null && index < length - 1) {
    object = object[path[index++]];
  }
  if (object && index === length - 1) {
    object[path[index]] = val;
    return true;
  } else {
    return false;
  }
};

export var getDelta = function (instance) {
  var changedKeys, i, k, len, ret;
  changedKeys = instance.changed();
  if (!changedKeys) {
    return false;
  }
  ret = {};
  for (i = 0, len = changedKeys.length; i < len; i++) {
    k = changedKeys[i];
    ret[k] = instance.dataValues[k];
  }
  return ret;
};